resolver: lts-22.22
packages:
- linkcheck

extra-deps:
- github: NorfairKing/opt-env-conf
  commit: 2e6aaaa65eb3f5008b05c28adc29312bd8a47d46
  subdirs:
    - opt-env-conf
    - opt-env-conf-test

- github: NorfairKing/safe-coloured-text
  commit: a58b782acc873a40a0eeb20eb4dc22c6df9c9dee
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-layout
    - safe-coloured-text-terminfo

- github: NorfairKing/autodocodec
  commit: 36779707f38ec3aeb0a591ff8043a63717c96ea2
  subdirs:               
    - autodocodec  
    - autodocodec-schema  
    - autodocodec-yaml                            
system-ghc: true
nix:
  enable: false
with-hpack: hpack

