resolver: lts-23.19
packages:
- linkcheck

extra-deps:
- github: NorfairKing/opt-env-conf
  commit: 2e6aaaa65eb3f5008b05c28adc29312bd8a47d46
  subdirs:
    - opt-env-conf
    - opt-env-conf-test

- github: NorfairKing/safe-coloured-text
  commit: 26b7657428f277f819a0831cbddddb7f4c5408f9
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-layout
    - safe-coloured-text-terminfo

- github: NorfairKing/autodocodec
  commit: b435803c3367b06c0d38acd90a54ba63e63fb6be
  subdirs:               
    - autodocodec
    - autodocodec-nix
    - autodocodec-schema  
    - autodocodec-yaml                            
system-ghc: true
nix:
  enable: false
with-hpack: hpack

