name:                linkcheck
version:             0.0.0.0
github:              "NorfairKing/linkcheck"
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - conduit
    - containers
    - envparse
    - http-client
    - http-client-tls
    - http-types
    - monad-logger
    - network-uri
    - optparse-applicative
    - path
    - path-io
    - stm
    - tagsoup
    - text
    - unliftio
    - unliftio
    - yamlparse-applicative

executables:
  linkcheck:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optP-Wno-nonportable-include-path # For macos
    dependencies:
    - linkcheck

tests:
  linkcheck-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - linkcheck
